#!/bin/csh
#tupleMetric: tupleMetric.cpp
	icpc -std=c++11 -g ../CodeWriting/tupleMetric.cpp ../Modules/Mode.cpp ../Modules/EigSolver.cpp ../UtilityFunc/ghQuad.cpp ../Modules/Potential_mod.cpp ../UtilityFunc/aux.cpp ../Modules/cpot.cpp -o tupleMetric -I${MKLROOT}/include  ${MKLROOT}/lib/intel64/libmkl_scalapack_lp64.a -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_intel_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_blacs_intelmpi_lp64.a -Wl,--end-group -liomp5 -lpthread -lm -ldl 
